# Generated by Django 4.1.6 on 2023-02-16 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_alter_produto_variations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='variations',
            field=models.ManyToManyField(blank=True, null=True, to='produtos.variation'),
        ),
    ]
