# Generated by Django 4.1.6 on 2023-02-18 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0005_alter_produto_variations'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='peso',
            field=models.DecimalField(decimal_places=2, default=0.04, max_digits=10),
        ),
        migrations.AddField(
            model_name='variation',
            name='peso',
            field=models.DecimalField(decimal_places=2, default=0.04, max_digits=10),
        ),
    ]
