# Generated by Django 4.1.6 on 2023-02-20 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0006_produto_peso_variation_peso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='variations',
            field=models.ManyToManyField(blank=True, to='produtos.variation'),
        ),
    ]
