# Generated by Django 3.1.12 on 2023-02-24 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0008_auto_20230224_1612'),
        ('produtos', '0007_auto_20230224_1618'),
    ]

    operations = [
    ]
