# Generated by Django 4.1.7 on 2023-02-26 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_alter_category_id_alter_produto_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='variations',
        ),
        migrations.AddField(
            model_name='produto',
            name='variations',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='produtos.variation'),
        ),
    ]
