# Generated by Django 4.1.7 on 2023-02-26 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_remove_produto_variations_produto_variations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='variations',
        ),
        migrations.AddField(
            model_name='variation',
            name='nome_simplificado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='variation',
            name='produto_pai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='produtos.produto'),
        ),
    ]
