# Generated by Django 4.1.7 on 2023-02-27 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0006_materiaprima_variation_materia_prima'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='gasto',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
