# Generated by Django 4.1.7 on 2023-02-28 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0007_variation_gasto'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='unidade',
            field=models.CharField(default='unidade', max_length=100),
        ),
    ]
