# Generated by Django 4.1.7 on 2023-02-28 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0008_variation_unidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiaprima',
            name='unidade',
            field=models.CharField(default='unidade', max_length=100),
        ),
    ]
