# Generated by Django 4.1.7 on 2023-03-04 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0009_materiaprima_unidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiaprima',
            name='unidade',
            field=models.CharField(default='mls', max_length=100),
        ),
    ]
