# Generated by Django 4.1.6 on 2023-02-17 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_cartitem_variation'),
        ('pedidos', '0002_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='itens',
            field=models.ManyToManyField(to='cart.cartitem'),
        ),
    ]
