# Generated by Django 4.1.7 on 2023-03-06 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_pedidoitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='numero_pedido_tiny',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('Aguardando pagamento', 'Aguardando pagamento'), ('Em processamento', 'Em processamento'), ('Pago', 'Pago'), ('Em trânsito', 'Em trânsito'), ('Entregue', 'Entregue'), ('Cancelado', 'Cancelado')], default='Aguardando pagamento', max_length=20),
        ),
    ]
