# Generated by Django 4.1.7 on 2023-03-07 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_pedido_numero_pedido_tiny_alter_pedido_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='mercado_pago_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
