# Generated by Django 4.1.7 on 2023-03-09 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_pedido_mercado_pago_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='metodo_de_pagamento',
            field=models.CharField(choices=[('MercadoPago', 'MercadoPago'), ('Pix', 'Pix'), ('Deposito', 'Deposito'), ('Pagseguro', 'Pagseguro')], default='Nao selecionado', max_length=20),
        ),
    ]
