# Generated by Django 4.1.6 on 2023-02-19 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0006_alter_pedido_metodo_de_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='valor_frete',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
    ]
