# Generated by Django 4.1.6 on 2023-02-20 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0010_alter_pedido_itens'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='comprovante',
            field=models.FileField(blank=True, null=True, upload_to='comprovantes'),
        ),
    ]
