# Generated by Django 4.1.6 on 2023-02-18 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_pedido_itens'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='frete',
            field=models.CharField(choices=[('Sedex', 'Sedex'), ('PAC', 'PAC')], default='Frete nao selecionado', max_length=20),
        ),
    ]
