# Generated by Django 4.1.6 on 2023-02-19 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_pedido_frete'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='metodo_de_pagamento',
            field=models.CharField(choices=[('Cartao', 'Cartao'), ('Pix', 'Pix'), ('Deposito', 'Deposito'), ('Pagseguro', 'Pagseguro')], default='Aguardando pagamento', max_length=20),
        ),
        migrations.AddField(
            model_name='pedido',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='total',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
