# Generated by Django 4.1.6 on 2023-02-19 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0008_pedidoitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidoitem',
            name='pedido',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='itens',
            field=models.ManyToManyField(to='pedidos.pedidoitem'),
        ),
    ]
