# Generated by Django 4.1.6 on 2023-02-19 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0009_remove_pedidoitem_pedido_alter_pedido_itens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='itens',
            field=models.ManyToManyField(blank=True, default=1, to='pedidos.pedidoitem'),
        ),
    ]
