# Generated by Django 4.1.6 on 2023-02-17 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enderecoentrega',
            name='primario',
            field=models.BooleanField(default=True),
        ),
    ]
